{% set name = "spikeinterface" %}
{% set version = "0.103.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spikeinterface-{{ version }}.tar.gz
  sha256: 707cebd20994f32201ecace7241cbcbd7699a7e41e151d6a972f2858a003111d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - setuptools >=78.0.2
    - pip
  run:
    - python
    - numpy >=1.20  # [py<313]
    - numpy >=2.0.0  # [py>=313]
    - threadpoolctl >=3.0.0
    - tqdm
    - zarr >=2.18,<3
    - python-neo >=0.14.1
    - probeinterface >=0.3.0
    - packaging
    - pydantic
    - numcodecs <0.16.0
  run_constrained:
    # As of 0.101.1, the minimum supported version of Kilosort4 is 4.0.16:
    # https://github.com/SpikeInterface/spikeinterface/pull/3339
    - kilosort >=4.0.16

test:
  imports:
    - spikeinterface
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/SpikeInterface/spikeinterface
  summary: Python toolkit for analysis, visualization, and comparison of spike sorting output
  license: MIT
  license_file: LICENSE
  doc_url: https://spikeinterface.readthedocs.io/
  dev_url: https://github.com/SpikeInterface/spikeinterface

extra:
  recipe-maintainers:
    - dhmjhu
