{% set name = "spikeinterface" %}
{% set version = "0.101.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spikeinterface-{{ version }}.tar.gz
  sha256: e06db61eebd7f516b9e5e543599962ed4fd8d266ccd5184eef933f00935b7176

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=62.0
    - pip
  run:
    - python >=3.9,<4.0
    - numpy >=1.20,<2.0
    - threadpoolctl >=3.0.0
    - tqdm
    - zarr >=2.16,<2.18
    - python-neo >=0.13.0
    - probeinterface >=0.2.23
    - packaging

test:
  imports:
    - spikeinterface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SpikeInterface/spikeinterface
  summary: Python toolkit for analysis, visualization, and comparison of spike sorting output
  license: MIT
  license_file: LICENSE
  doc_url: https://spikeinterface.readthedocs.io/
  dev_url: https://github.com/SpikeInterface/spikeinterface

extra:
  recipe-maintainers:
    - dhmjhu
