{% set name = "spikeinterface" %}
{% set version = "0.101.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spikeinterface-{{ version }}.tar.gz
  sha256: a538fdce2601556baaba0e1caa2fcfce3b840f755bba69437a7a0a29601114d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9,<4.0
    - setuptools >=62.0
    - pip
  run:
    - python >=3.9,<4.0
    - numpy >=1.20,<2.0
    - threadpoolctl >=3.0.0
    - tqdm
    - zarr >=2.16,<2.18
    - python-neo >=0.13.0
    - probeinterface >=0.2.23
    - packaging
  run_constrained:
    # As of 0.101.1, the minimum supported version of Kilosort4 is 4.0.16:
    # https://github.com/SpikeInterface/spikeinterface/pull/3339
    - kilosort >=4.0.16

test:
  imports:
    - spikeinterface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SpikeInterface/spikeinterface
  summary: Python toolkit for analysis, visualization, and comparison of spike sorting output
  license: MIT
  license_file: LICENSE
  doc_url: https://spikeinterface.readthedocs.io/
  dev_url: https://github.com/SpikeInterface/spikeinterface

extra:
  recipe-maintainers:
    - dhmjhu
